default:
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS: []
  DATABASE_URL: ""

heroku:
  DEBUG: false
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - benzak.herokuapp.com

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
