default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  TELEGRAM_BENZAKBOT_TOKEN: ""

development:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
  DEBUG: true

heroku:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - benzak.herokuapp.com
  DEBUG: false

travis:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
  DATABASE_URL: "postgresql://postgres@localhost:5432/benzak"
  DEBUG: true
  SECRET_KEY: "xxx"
  TELEGRAM_BENZAKBOT_TOKEN: "1"
