default:
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS: []
  DATABASE_URL: ""

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost

heroku:
  DEBUG: false
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - benzak.herokuapp.com

travis:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
  SECRET_KEY: "xxx"
  DATABASE_URL: "postgresql://postgres@localhost:5432/benzak"
